Season = require 'season'
Path = require 'path'
{ File } = require 'atom'

class ThemeManager
    constructor: ->
        try
            cson = Path.join __dirname, 'themes.cson'
            @themes = Season.readFileSync cson
        catch err
            atom.notifications.addError 'error reading or parsing theme cson file while generating config',
                detail: err.message,
                dismissable: yes
        name = atom.config.get('theme-jetbrains-syntax.theme') ? 'light'
        @curTheme = @find name
        @colorStylesheet = new File Path.join __dirname, '..', 'style', 'colors.less'

    get: ->
        @curTheme

    set: (name) ->
        @curTheme = @find name
        atom.config.set 'theme-jetbrains-syntax.palette', @curTheme

    find: (name) ->
        switch name
            when 'light' then @themes.jetbrains_light
            when 'dark' then @themes.jetbrains_dark
            when 'darcula' then @themes.jetbrains_darcula
            else
                atom.notifications.addError 'unknown theme',
                    detail: name,
                    dismissable: yes
                name = null

    reset: ->
        curPalette = atom.config.get 'theme-jetbrains-syntax.palette'
        if (color.isEqual @curTheme[name] for name, color of curPalette).every Boolean
            @refresh curPalette
        else
            atom.config.set 'theme-jetbrains-syntax.palette', @curTheme


    refresh: (palette) ->
        less = """
               // These colors are specific to the theme. Do not use in a package!
               // Autogenerated by theme-jetbrains-syntax. Do not edit!

               #{("@#{name}: #{color.toHexString()};" for name, color of palette).join '\n'}
               """
               
        @colorStylesheet.write less
            .then ->
                setTimeout ->
                    atom.themes.reloadBaseStylesheets()
                    for pack in atom.packages.getActivePackages() when pack.getType() is 'atom' and pack.getStylesheetPaths().length
                        pack.reloadStylesheets()

                    for theme in atom.themes.getActiveThemes()
                        theme.reloadStylesheets()

                    atom.notifications.addSuccess 'done!',
                        detail: 'stylesheets reloaded'
                        dismissable: yes
                , 100
            .catch (err) ->
                atom.notifications.addError 'error writing new less stylesheet file',
                    detail: err.message,
                    dismissable: yes

        atom.notifications.addInfo 'refreshing',
            detail: 'please be patient...'
            dismissable: yes

module.exports = ThemeManager